"""add_driver_location_eta_to_bookings

Revision ID: 0c2c0e84ef3a
Revises: 17a48c062296
Create Date: 2026-06-29 22:42:34.205962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2c0e84ef3a'
down_revision: Union[str, Sequence[str], None] = '17a48c062296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('driver_accept_lat', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('driver_accept_lng', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('eta_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'eta_minutes')
    op.drop_column('bookings', 'driver_accept_lng')
    op.drop_column('bookings', 'driver_accept_lat')
    # ### end Alembic commands ###
